// src/App.jsx
import { mapGetters } from 'vuex' 
export default {
  data () {
    return {
      increment: 0
    }
  },
  computed: {
    ...mapGetters([
      'planets'
    ])
  },
  mounted () {
    this.$store.dispatch('FETCH_PLANETS')
  },
  methods: {
    handleIncrement () {
      this.increment++
    },
    printPlanets (h) {
      return (
        <ul>
          {this.planets.items.map((item, key) => (
            <li key={key}>{item.name}</li>
          ))}
        </ul>
      )
    },
    renderPlanets (h) {
      switch (this.planets.status) {
        case 'fetched':
          return this.printPlanets(h)
          break
        case 'fetching':
          return (
            <div>
              Loading...
            </div>
          )
          break
        case 'error':
          return (
            <div>
              Something Error
            </div>
          )
          break
        default:
          break
      }
    }
  },
  render(h) {
    return (
      <div>
        <h1>Vue with jsx</h1>
        this is increment {this.increment} <br/>
        <button onClick={this.handleIncrement}>add+</button>
        {this.renderPlanets(h)}
      </div>
    )
  }
}

// src/App.vue
<template>
  <div id="app">
    <h1>Ardian Planets</h1>
    <span v-if="planets.status === 'fetching'">Loading...</span>
    <span v-if="planets.status === 'error'">Something Error</span>
    <ul v-if="planets.status === 'fetched'">
      <li v-for="(planet, index) in planets.items" :key="index">
        {{ planet.name }}
      </li>
    </ul>
  </div>
</template>

<script>
  import { mapGetters } from 'vuex' 
  export default {
    computed: {
      ...mapGetters([
        'planets'
      ])
    },
    mounted () {
      this.$store.dispatch('FETCH_PLANETS')
    }
  }
</script>
